runtime: python311

instance_class: F2
automatic_scaling:
  min_instances: 2
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

env_variables:
  DATABASE_URL: ${DATABASE_URL}
  REDIS_URL: ${REDIS_URL}
  SECRET_KEY: ${SECRET_KEY}

handlers:
- url: /.*
  script: auto

